# dvge/constants/__init__.py

"""Constants package for DVGE."""

from .colors import *
from .fonts import *
from .dimensions import *

__all__ = [
    # Colors
    'COLOR_BACKGROUND', 'COLOR_CANVAS_BACKGROUND', 'COLOR_GRID_LINES',
    'COLOR_PRIMARY_FRAME', 'COLOR_SECONDARY_FRAME', 'COLOR_TEXT',
    'COLOR_TEXT_MUTED', 'COLOR_ACCENT', 'COLOR_ACCENT_HOVER',
    'COLOR_SUCCESS', 'COLOR_WARNING', 'COLOR_ERROR', 'COLOR_DANGER', 'COLOR_COMBAT',
    'COLOR_QUEST_ACTIVE', 'COLOR_QUEST_COMPLETED', 'COLOR_QUEST_FAILED',
    'NODE_DEFAULT_COLOR', 'NODE_INTRO_COLOR', 'NODE_COMBAT_COLOR',
    'NODE_SELECTED_OUTLINE_COLOR', 'NODE_CONNECTION_COLOR',
    
    # Fonts
    'FONT_FAMILY', 'FONT_TITLE', 'FONT_SUBTITLE', 'FONT_SUBTITLE_SMALL', 
    'FONT_SMALL', 'FONT_NPC', 'FONT_DIALOGUE', 'FONT_OPTION', 
    'FONT_ADD_BUTTON', 'FONT_PROPERTIES_LABEL', 'FONT_PROPERTIES_ENTRY', 
    'FONT_ICON',
    
    # Dimensions
    'NODE_WIDTH', 'NODE_HEADER_HEIGHT', 'NODE_BASE_BODY_HEIGHT',
    'OPTION_LINE_HEIGHT', 'NODE_FOOTER_HEIGHT', 'NODE_BORDER_RADIUS',
    'GRID_SIZE'
]