# dvge/constants/colors.py

"""Color constants for the DVGE application."""

# --- UI THEME COLORS ---
COLOR_BACKGROUND = "#242424"
COLOR_CANVAS_BACKGROUND = "#1E1E1E"
COLOR_GRID_LINES = "#2C2C2C"
COLOR_PRIMARY_FRAME = "#2A2D2E"
COLOR_SECONDARY_FRAME = "#323232"
COLOR_TEXT = "#DCE4EE"
COLOR_TEXT_MUTED = "#8A95A0"
COLOR_ACCENT = "#00AFFF"
COLOR_ACCENT_HOVER = "#0095DD"
COLOR_SUCCESS = "#2ECC71"
COLOR_WARNING = "#F1C40F"
COLOR_ERROR = "#E74C3C"
COLOR_DANGER = "#E74C3C"

# --- COMBAT RELATED COLORS ---
COLOR_COMBAT = "#C0392B"

# --- QUEST STATUS COLORS ---
COLOR_QUEST_ACTIVE = "#F1C40F"
COLOR_QUEST_COMPLETED = "#2ECC71"
COLOR_QUEST_FAILED = "#E74C3C"

# --- NODE COLORS ---
NODE_DEFAULT_COLOR = "#3A3A3A"
NODE_INTRO_COLOR = "#006400"
NODE_COMBAT_COLOR = "#882d23"
NODE_SELECTED_OUTLINE_COLOR = COLOR_ACCENT
NODE_CONNECTION_COLOR = COLOR_ACCENT