# dvge/constants.py

# --- UI THEME COLORS ---
COLOR_BACKGROUND = "#242424"
COLOR_CANVAS_BACKGROUND = "#1E1E1E"
COLOR_GRID_LINES = "#2C2C2C"
COLOR_PRIMARY_FRAME = "#2A2D2E"
COLOR_SECONDARY_FRAME = "#323232"
COLOR_TEXT = "#DCE4EE"
COLOR_TEXT_MUTED = "#8A95A0"
COLOR_ACCENT = "#00AFFF"
COLOR_ACCENT_HOVER = "#0095DD"
COLOR_SUCCESS = "#2ECC71"
COLOR_WARNING = "#F1C40F"
COLOR_ERROR = "#E74C3C"
COLOR_COMBAT = "#C0392B" # Color for combat-related elements

# --- NODE VISUALS ---
NODE_WIDTH = 300
NODE_HEADER_HEIGHT = 40
NODE_BASE_BODY_HEIGHT = 80
OPTION_LINE_HEIGHT = 28
NODE_FOOTER_HEIGHT = 35
GRID_SIZE = 25
NODE_BORDER_RADIUS = 12
NODE_DEFAULT_COLOR = "#3A3A3A"
NODE_INTRO_COLOR = "#006400"
NODE_COMBAT_COLOR = "#882d23"
NODE_SELECTED_OUTLINE_COLOR = COLOR_ACCENT
NODE_CONNECTION_COLOR = COLOR_ACCENT

# --- FONT DEFINITIONS ---
try:
    FONT_FAMILY = "Roboto"
except:
    FONT_FAMILY = "Segoe UI"

FONT_TITLE = (FONT_FAMILY, 16, "bold")
FONT_NPC = (FONT_FAMILY, 13, "bold")
FONT_DIALOGUE = (FONT_FAMILY, 11)
FONT_OPTION = (FONT_FAMILY, 11, "italic")
FONT_ADD_BUTTON = (FONT_FAMILY, 11, "bold")
FONT_PROPERTIES_LABEL = (FONT_FAMILY, 12, "bold")
FONT_PROPERTIES_ENTRY = (FONT_FAMILY, 11)
FONT_ICON = ("Segoe UI Symbol", 14)
